### ISSUE TITLE
jupyter_bokeh an Jupyterlab 3

### ISSUE THREAD

**Issue by Bob-May** [bokeh/jupyter_bokeh#118] opened 2021-01-28 21:38 UTC
Following the directions here https://docs.bokeh.org/en/latest/docs/user_guide/jupyter.html fails with Jupyerlab 3.

`jupyter labextension install @bokeh/jupyter_bokeh
An error occured.
ValueError: The extension "@bokeh/jupyter_bokeh" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab                        Extension      Package
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/application
>=3.0.2 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/apputils
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/notebook
>=3.0.2 <3.1.0                    >=2.0.1 <3.0.0 @jupyterlab/rendermime-interfaces
>=6.0.2 <6.1.0                    >=5.0.2 <6.0.0 @jupyterlab/services
See the log file for details:  /tmp/jupyterlab-debug-6px5s7p2.log
`
[jupyterlab-debug-6px5s7p2.log](https://github.com/bokeh/jupyter_bokeh/files/5890126/jupyterlab-debug-6px5s7p2.log)

**Comment by bryevdv** [comment] 2021-01-28 21:45
duplicate of #116

**Closed by bryevdv** 2021-01-28 21:45 UTC

**Comment by Bob-May** [comment] 2021-01-28 22:04
As a user, I follow your published instructions and they do not work.

I follow the trail of issues, and I do not find a solution.

https://github.com/bokeh/jupyter_bokeh/issues/116 --> https://github.com/bokeh/bokeh/issues/10569 --> https://github.com/jupyter/docker-stacks/pull/1222

Which seems to say that the thing I reported as broken is still broken.  So how is the issue closed?

I do appreciate the team's efforts, and wish I were sufficiently skilled to contribute directly to a solution.

I get that it might take time for various things to flow into wherever, and that it might take some time to update the instructions on the web page.  If that's the case, just say so.

**Comment by bryevdv** [comment] 2021-01-28 22:21
@Bob-May I closed this issue because it is a duplicate, there is already another open issue that covers this. In the trail of issues you cite, there is https://github.com/bokeh/bokeh/issues/10569 which is open. This work is not done yet.
