### ISSUE TITLE
The extension "@bokeh/jupyter_bokeh" does not yet support the current version of JupyterLab.

### ISSUE THREAD

**Issue by lisaLee2021** [bokeh/jupyter_bokeh#117] opened 2021-01-26 08:05 UTC
The version of jupyter lab is 3.0.5. When install "@bokeh/jupyter_bokeh" , there is an error:

jupyter labextension install @bokeh/jupyter_bokeh

An error occured.
ValueError: The extension "@bokeh/jupyter_bokeh" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab                        Extension      Package
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/application
>=3.0.2 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/apputils
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/notebook
>=3.0.2 <3.1.0                    >=2.0.1 <3.0.0 @jupyterlab/rendermime-interfaces
>=6.0.2 <6.1.0                    >=5.0.2 <6.0.0 @jupyterlab/services

Is there a compatible version of jupyter_bokeh for  jupyterlab 3.0.5 ?
Please take a look, thanks!

**Comment by bryevdv** [comment] 2021-01-27 19:11
duplicate of #116

**Closed by bryevdv** 2021-01-27 19:11 UTC
